name: fasion_flare_ggpp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  shared_preferences: ^2.2.2

flutter_native_splash:
  color: "#43B3AE"
  image: assets/Images/0 txt logo1.png
  android_gravity: center

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/Images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Montserrat
      fonts:
        - asset: Fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: Fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: Fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: Fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: Fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: Fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: Fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: Fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: Fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: Fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: Fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: Fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: Fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: Fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: Fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: Fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: Fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: Fonts/Poppins/Poppins-Black.ttf
          weight: 900
  
